"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CheckCircle, ShieldCheck, UserPlus, UsersThree } from "@phosphor-icons/react";
import { clientApi } from "../../../../lib/client-api";
import { useI18n } from "../../../../components/I18nProvider";
type Membership = { user: { id: string; email: string; displayName: string; isActive: boolean; createdAt: string }; role: { code: string; name: string } };
type Role = { code: string; name: string; permissions: { permission: { code: string; name: string } }[] };
const ROLE_AR: Record<string,string> = { ADMIN:"مدير النظام", SALES_MANAGER:"مدير مبيعات", SALES_AGENT:"مسؤول مبيعات", VIEWER:"مشاهد" };
export default function UsersAccessPage(){
 const {locale}=useI18n(), ar=locale==="ar"; const [users,setUsers]=useState<Membership[]>([]),[roles,setRoles]=useState<Role[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const [u,r]=await Promise.all([clientApi<Membership[]>("/api/backend/admin/users"),clientApi<Role[]>("/api/backend/admin/users/roles")]);setUsers(u);setRoles(r)}
 useEffect(()=>{load().catch(()=>setMessage(ar?"تعذر تحميل المستخدمين":"Could not load users"))},[ar]);
 const admin=useMemo(()=>users.find(x=>x.user.email.toLowerCase()==="islam@kynox.io"),[users]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget;try{await clientApi("/api/backend/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await load();setMessage(ar?"تم إنشاء المستخدم وتعيين الدور":"User created and role assigned")}catch(x){setMessage(x instanceof Error?x.message:String(x))}finally{setBusy(false)}}
 async function update(id:string,patch:{roleCode?:string;isActive?:boolean}){setBusy(true);setMessage("");try{await clientApi(`/api/backend/admin/users/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});await load()}catch(x){setMessage(x instanceof Error?x.message:String(x))}finally{setBusy(false)}}
 return <main className="access-admin" dir={ar?"rtl":"ltr"}><section className="access-hero"><div><span className="access-kicker">KYNOX · RBAC</span><h1>{ar?"المستخدمون والصلاحيات":"Users and permissions"}</h1><p>{ar?"إدارة وصول فريق المبيعات وفق مبدأ أقل صلاحية، مع سجل تدقيق لكل تغيير.":"Least-privilege sales-team access with an audit trail for every change."}</p></div><ShieldCheck size={54} weight="duotone"/></section>
 {admin?<div className="access-notice"><CheckCircle size={20} weight="fill"/>{ar?"حساب المدير المحفوظ: ":"Protected administrator: "}<strong>{admin.user.email}</strong></div>:null}{message?<div className="access-message">{message}</div>:null}
 <section className="access-grid"><article className="access-panel"><h2><UsersThree size={24}/>{ar?"قائمة المستخدمين":"User directory"}</h2><div className="access-table-wrap"><table><thead><tr><th>{ar?"المستخدم":"User"}</th><th>{ar?"الدور":"Role"}</th><th>{ar?"الحالة":"Status"}</th><th>{ar?"الإجراء":"Action"}</th></tr></thead><tbody>{users.map(({user,role})=><tr key={user.id}><td><strong>{user.displayName}</strong><small>{user.email}</small></td><td><select value={role.code} disabled={busy||user.email.toLowerCase()==="islam@kynox.io"} onChange={e=>update(user.id,{roleCode:e.target.value})}>{roles.map(r=><option key={r.code} value={r.code}>{ar?ROLE_AR[r.code]:r.name}</option>)}</select></td><td><span className={user.isActive?"status-active":"status-inactive"}>{user.isActive?(ar?"نشط":"Active"):(ar?"موقوف":"Inactive")}</span></td><td><button className="button button-secondary" disabled={busy||user.email.toLowerCase()==="islam@kynox.io"} onClick={()=>update(user.id,{isActive:!user.isActive})}>{user.isActive?(ar?"إيقاف":"Deactivate"):(ar?"تفعيل":"Activate")}</button></td></tr>)}</tbody></table></div></article>
 <aside className="access-panel"><h2><UserPlus size={24}/>{ar?"إضافة مستخدم":"Add user"}</h2><form className="access-form" onSubmit={create}><label>{ar?"الاسم":"Name"}<input name="displayName" required minLength={2}/></label><label>{ar?"البريد الإلكتروني":"Email"}<input name="email" type="email" required/></label><label>{ar?"كلمة مرور مؤقتة":"Temporary password"}<input name="temporaryPassword" type="password" required minLength={12} autoComplete="new-password"/></label><label>{ar?"الدور":"Role"}<select name="roleCode" required>{roles.map(r=><option key={r.code} value={r.code}>{ar?ROLE_AR[r.code]:r.name}</option>)}</select></label><button className="button button-primary" disabled={busy}>{ar?"إنشاء المستخدم":"Create user"}</button></form></aside></section>
 <section className="access-panel role-matrix"><h2>{ar?"مصفوفة الأدوار":"Role matrix"}</h2><div className="role-cards">{roles.map(r=><article key={r.code}><strong>{ar?ROLE_AR[r.code]:r.name}</strong><span>{r.permissions.length} {ar?"صلاحية":"permissions"}</span><details><summary>{ar?"عرض التفاصيل":"View details"}</summary><ul>{r.permissions.map(({permission})=><li key={permission.code}>{permission.code}</li>)}</ul></details></article>)}</div></section></main>
}
