export type SalesCopyKey =
  | "eyebrow" | "title" | "subtitle" | "newContact" | "newOpportunity" | "refresh"
  | "myWork" | "leads" | "contacts" | "opportunities" | "activities" | "tasks"
  | "attention" | "overdue" | "today" | "open" | "completed" | "empty"
  | "contactName" | "email" | "phone" | "preference" | "saveContact" | "contactSaved"
  | "opportunityName" | "stage" | "project" | "unit" | "createOpportunity" | "opportunityCreated"
  | "activityNote" | "activityType" | "logActivity" | "activityLogged"
  | "taskTitle" | "dueDate" | "priority" | "assignee" | "createTask" | "taskCreated" | "complete"
  | "quotation" | "quotationHelp" | "createQuotation" | "quotationCreated" | "revision" | "customerDecision"
  | "serverError" | "loading" | "synthetic" | "availabilityNote" | "noPermission"
  | "overview" | "quickActions" | "selectedContext" | "timeline" | "taskQueue" | "openWork"
  | "close" | "cancel" | "drawerHint" | "customer" | "owner" | "projectUnit" | "latestActivity"
  | "noOpportunity" | "emptyWork" | "viewContext" | "activityHistory" | "status" | "workload";

const en: Record<SalesCopyKey, string> = {
  eyebrow: "Sales operating workspace", title: "Command Center", subtitle: "A focused queue for buyer context, follow-up, opportunity movement and governed commercial actions.", newContact: "New contact", newOpportunity: "New opportunity", refresh: "Refresh", myWork: "My Work", leads: "Leads", contacts: "Contacts", opportunities: "Opportunities", activities: "Activities", tasks: "Tasks", attention: "What requires attention", overdue: "Overdue", today: "Due today", open: "Open", completed: "Completed", empty: "Nothing requires attention in this view.", contactName: "First name", email: "Email", phone: "Phone", preference: "Preferred channel", saveContact: "Save contact", contactSaved: "Contact saved.", opportunityName: "Opportunity name", stage: "Stage", project: "Project ID", unit: "Unit ID", createOpportunity: "Create opportunity", opportunityCreated: "Opportunity created.", activityNote: "What happened?", activityType: "Activity type", logActivity: "Log activity", activityLogged: "Activity added to the timeline.", taskTitle: "Task title", dueDate: "Due date", priority: "Priority", assignee: "Assignee user ID", createTask: "Create task", taskCreated: "Task created.", complete: "Complete", quotation: "Quotation", quotationHelp: "Quotation creation uses the frozen revision workflow. A quotation is not a reservation or payment confirmation.", createQuotation: "Create quotation", quotationCreated: "Quotation created with revision 1.", revision: "Revision", customerDecision: "Customer decision", serverError: "The server rejected this action. Review the fields and try again.", loading: "Loading…", synthetic: "Contract-backed surface", availabilityNote: "Unit availability remains authoritative in the reservation and inventory workflow.", noPermission: "You do not have permission to view this workspace.", overview: "Operating overview", quickActions: "Quick actions", selectedContext: "Selected context", timeline: "Activity timeline", taskQueue: "Task queue", openWork: "Open work", close: "Close", cancel: "Cancel", drawerHint: "Actions open in context so the workspace stays focused.", customer: "Customer", owner: "Owner", projectUnit: "Project / unit", latestActivity: "Latest activity", noOpportunity: "Select an opportunity to continue.", emptyWork: "Your queue is clear.", viewContext: "View context", activityHistory: "History", status: "Status", workload: "Workload",
};

const ar: Record<SalesCopyKey, string> = {
  eyebrow: "مساحة تشغيل المبيعات", title: "مركز القيادة", subtitle: "قائمة مركزة لسياق المشتري والمتابعة وتحريك الفرص والإجراءات التجارية المحكومة.", newContact: "جهة اتصال جديدة", newOpportunity: "فرصة جديدة", refresh: "تحديث", myWork: "مهامي", leads: "العملاء المحتملون", contacts: "جهات الاتصال", opportunities: "الفرص", activities: "الأنشطة", tasks: "المهام", attention: "ما يحتاج إلى انتباه", overdue: "متأخر", today: "مستحق اليوم", open: "مفتوح", completed: "مكتمل", empty: "لا توجد إجراءات تتطلب الانتباه في هذا العرض.", contactName: "الاسم الأول", email: "البريد الإلكتروني", phone: "الهاتف", preference: "قناة التواصل المفضلة", saveContact: "حفظ جهة الاتصال", contactSaved: "تم حفظ جهة الاتصال.", opportunityName: "اسم الفرصة", stage: "المرحلة", project: "معرف المشروع", unit: "معرف الوحدة", createOpportunity: "إنشاء فرصة", opportunityCreated: "تم إنشاء الفرصة.", activityNote: "ماذا حدث؟", activityType: "نوع النشاط", logActivity: "تسجيل النشاط", activityLogged: "تمت إضافة النشاط إلى الخط الزمني.", taskTitle: "عنوان المهمة", dueDate: "تاريخ الاستحقاق", priority: "الأولوية", assignee: "معرف المستخدم المسؤول", createTask: "إنشاء مهمة", taskCreated: "تم إنشاء المهمة.", complete: "إكمال", quotation: "عرض السعر", quotationHelp: "إنشاء عرض السعر يستخدم مسار المراجعات المجمد. عرض السعر ليس حجزاً ولا تأكيداً للدفع.", createQuotation: "إنشاء عرض سعر", quotationCreated: "تم إنشاء عرض السعر بالمراجعة الأولى.", revision: "المراجعة", customerDecision: "قرار العميل", serverError: "رفض الخادم هذا الإجراء. راجع الحقول وحاول مرة أخرى.", loading: "جارٍ التحميل…", synthetic: "واجهة مرتبطة بالعقد", availabilityNote: "تبقى إتاحة الوحدة مرجعية في مسار الحجوزات والمخزون.", noPermission: "لا تملك صلاحية عرض مساحة العمل هذه.", overview: "نظرة تشغيلية", quickActions: "إجراءات سريعة", selectedContext: "السياق المحدد", timeline: "الخط الزمني للنشاط", taskQueue: "قائمة المهام", openWork: "العمل المفتوح", close: "إغلاق", cancel: "إلغاء", drawerHint: "تفتح الإجراءات في سياقها للحفاظ على تركيز مساحة العمل.", customer: "العميل", owner: "المالك", projectUnit: "المشروع / الوحدة", latestActivity: "آخر نشاط", noOpportunity: "حدد فرصة للمتابعة.", emptyWork: "قائمتك خالية.", viewContext: "عرض السياق", activityHistory: "السجل", status: "الحالة", workload: "عبء العمل",
};

export function salesText(locale: "en" | "ar", key: SalesCopyKey) {
  return (locale === "ar" ? ar : en)[key];
}
